server {
    listen       80;
    listen      [::]:80;
    server_name  blue.192.168.170.136.nip.io;
    
    add_header X-MY-Header "My blue.nip.io content!";

    location / {
        root   /usr/share/nginx/html/blue.nip.io-public;
        index  index.html index.htm;
        try_files $uri $uri/ =404;
    }


    error_page 404 /404.html;

    location = /404.html {
        root /usr/share/nginx/html/blue.nip.io-public;
        # Mark as internal to prevent direct external access
        internal;
    }


    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html/blue.nip.io-public;
        # Mark as internal to prevent direct external access
        internal;
    }
}
