server {
    listen       80 default_server;
    listen      [::]:80 default_server;
    server_name  localhost;
    
    add_header X-MY-Header "My default_server content!";

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html/default-public;
        index  index.html index.htm;
        try_files $uri $uri/ =404;
    }


    error_page 404 /404.html;

    location = /404.html {
        root /usr/share/nginx/html/default-public;
        # Mark as internal to prevent direct external access
        internal;
    }


    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html/default-public;
        # Mark as internal to prevent direct external access
        internal;
    }



    ##############################################################
    #                                                            #
    # proxy the PHP scripts to Apache listening on 127.0.0.1:80  #
    #                                                            #
    ##############################################################
    # location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    # }



    ##############################################################
    #                                                            #
    # proxy the PY scripts to Gunicorn listening on 127.0.0.1:80 #
    #                                                            #
    ##############################################################
    # Serve static files directly
    # location /static/ {
    #     alias /path/to/your/django/static/files/; # Specify the path to your 'collectstatic' directory
    # }

    # Pass all other requests to the Gunicorn socket/port
    # location / {
    #     proxy_pass http://127.0.0.1:80;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    # }
}
